version: "3.9"

services:
  washapp-db:
    build: ./database
    container_name: washapp-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: washappDatabase
      POSTGRES_USER: washapp
      POSTGRES_PASSWORD: washapp123
    volumes:
      - washapp-db-data:/var/lib/postgresql/data

  washapp-backend:
    build:
      context: ./Spring-back
      dockerfile: Dockerfile
    container_name: washapp-backend
    depends_on:
      - washapp-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://washapp-db:5432/washappDatabase
      SPRING_DATASOURCE_USERNAME: washapp
      SPRING_DATASOURCE_PASSWORD: washapp123
    restart: unless-stopped

  washapp-tests:
    image: gradle:8.10.2-jdk21-alpine
    working_dir: /workspace
    volumes:
      - ./Spring-back:/workspace
      - gradle-cache:/home/gradle/.gradle
    command: ["./gradlew", "test", "--no-daemon"]
    depends_on:
      - washapp-db

  washapp-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: washapp-frontend
    depends_on:
      - washapp-backend
    ports:
      - "8081:8081"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      EXPO_TELEMETRY_DISABLED: "1"
      EXPO_PACKAGER_PORT: "8081"
      REACT_NATIVE_PACKAGER_HOSTNAME: "localhost"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    tty: true
    stdin_open: true

    command: >
      sh -lc "npm ci --no-audit --no-fund || npm install --no-audit --no-fund;
      npx --yes expo start --web --port 8081 --host localhost --clear"

volumes:
  washapp-db-data:
  gradle-cache:
